export const images = {
  heroBg: "/images/hero-bg.jpg",
  heroCar: "/images/hero-car.jpg",
  importance: "/images/importance.jpg",
  steamWash: "/images/steam-wash.jpg",
  mobileService: "/images/mobile-service.jpg",
  beforeAfter: {
    exteriorBefore: "/images/before-after/exterior-before.jpg",
    exteriorAfter: "/images/before-after/exterior-after.jpg",
    seatBefore: "/images/before-after/seat-before.jpg",
    seatAfter: "/images/before-after/seat-after.jpg",
    backseatBefore: "/images/before-after/backseat-before.jpg",
    backseatAfter: "/images/before-after/backseat-after.jpg",
  },
  services: {
    exterior: "/images/service-exterior.jpg",
    polish: "/images/service-polish.jpg",
    engine: "/images/service-engine.jpg",
    wheels: "/images/service-wheels.jpg",
    interior: "/images/service-interior.jpg",
    paint: "/images/service-paint.jpg",
    glass: "/images/service-glass.jpg",
    tires: "/images/service-tires.jpg",
  },
} as const;
