export const images = {
  heroBg: "/images/hero-bg.jpg",
  heroCar: "/images/hero-car.jpg",
  importance: "/images/importance.jpg",
  steamWash: "/images/steam-wash.jpg",
  mobileService: "/images/mobile-service.png",
  beforeAfter: {
    slide1Before: "/images/before-after/1-before.jpeg",
    slide1After: "/images/before-after/1-after.jpeg",
    slide2Before: "/images/before-after/2-before.jpeg",
    slide2After: "/images/before-after/2-after.jpeg",
    slide3Before: "/images/before-after/3-before.jpeg",
    slide3After: "/images/before-after/3-after.jpeg",
  },
  services: {
    exterior: "/images/service-exterior.jpg",
    polish: "/images/service-polish.jpg",
    engine: "/images/service-engine.jpg",
    wheels: "/images/service-wheels.jpg",
    interior: "/images/service-interior.jpg",
    paint: "/images/service-paint.jpg",
    glass: "/images/service-glass.jpg",
    tires: "/images/service-tires.jpg",
  },
} as const;
